---
# tasks file for install openjdk for FreeBSD

- name: FreeBsd | Install openjre
  ansible.builtin.package:
    name: "{{ openjre_package }}"
    state: present
  when: openjre_install|bool

- name: FreeBSD | Install openjdk
  ansible.builtin.package:
    name: "{{ openjdk_package }}"
    state: present
  when: openjdk_install|bool
