---
# tasks file for install openjdk for Linux

- name: Debian | Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Archlinux | Update pacman cache
  community.general.pacman:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Archlinux"

- name: Suse | Update emerge cache
  ansible.builtin.command: zypper refresh
  changed_when: false
  when: ansible_os_family == "Suse"

- name: Gentoo | Update emerge cache
  ansible.builtin.command: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: Linux | Install openjre
  ansible.builtin.package:
    name: "{{ openjre_package }}"
    state: present
  when: openjre_install|bool

- name: Linux | Install openjdk
  ansible.builtin.package:
    name: "{{ openjdk_package }}"
    state: present
  when: openjdk_install|bool
