---
# tasks file for install openjdk for Macosx

- name: Darwin | List users
  ansible.builtin.shell: |
    set -o pipefail
    ls -1 /Users/ |grep -v Shared |grep -v .localized
  register: list_users
  changed_when: false

- name: Darwin | Adoptopenjdk homebrew repository
  community.general.homebrew_tap:
    name: AdoptOpenJDK/openjdk
    state: present
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ list_users.stdout_lines }}"

- name: Darwin | Install openjdk
  community.general.homebrew_cask:
    name: "{{ openjdk_package }}"
    state: present
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ list_users.stdout_lines }}"
