---
# tasks file for install openjdk for Windows

- name: Windows | Install openjdk
  win_chocolatey:
    name: openjdk
    state: present

- name: Windows | Ensure java is on the glboal path
  win_path:
    elements: 'C:\Program Files\OpenJDK\jdk-15.0.1\bin'
